// ===== QUESTION BANK =====
const QUESTION_BANK = {
  1: {
    name: "Tổng quan Cloud",
    color: "c1",
    easy: [
      { q: "Điện toán đám mây (cloud computing) là:", opts: ["Hệ thống máy tính cá nhân","Mô hình cung cấp tài nguyên qua Internet","Phần mềm offline","Hệ điều hành"], ans: 1 },
      { q: "Cloud computing bắt nguồn từ ý tưởng:", opts: ["AI","Time-sharing","Blockchain","IoT"], ans: 1 },
      { q: "Người dùng cloud không cần quan tâm đến:", opts: ["Ứng dụng","Dữ liệu","Hạ tầng","Truy cập"], ans: 2 },
      { q: "Một đặc điểm của cloud là:", opts: ["Không có mạng","Truy cập qua Internet","Không có dữ liệu","Không có user"], ans: 1 },
      { q: "AWS được Amazon cung cấp vào năm:", opts: ["2000","2003","2006","2010"], ans: 2 },
      { q: "Một nhà cung cấp cloud lớn là:", opts: ["Google","CPU","RAM","BIOS"], ans: 0 },
      { q: "Cloud giúp:", opts: ["Tăng chi phí","Giảm chi phí","Không thay đổi chi phí","Không có chi phí"], ans: 1 },
      { q: "Cloud computing thuộc loại hệ thống:", opts: ["Tập trung","Phân tán","Offline","Standalone"], ans: 1 },
      { q: "Người dùng cloud truy cập dịch vụ thông qua:", opts: ["USB","Internet","CPU","RAM"], ans: 1 },
      { q: "Một lợi ích của cloud là:", opts: ["Không mở rộng","Mở rộng linh hoạt","Không có dữ liệu","Không truy cập"], ans: 1 },
    ],
    medium: [
      { q: "Cloud computing cho phép:", opts: ["Truy cập tài nguyên theo nhu cầu","Không truy cập","Không lưu trữ","Không xử lý"], ans: 0 },
      { q: "Một đặc tính của cloud theo NIST là:", opts: ["Không mạng","On-demand self-service","Không user","Không dữ liệu"], ans: 1 },
      { q: "Broad network access nghĩa là:", opts: ["Truy cập hạn chế","Truy cập rộng qua nhiều thiết bị","Không truy cập","Chỉ server"], ans: 1 },
      { q: "Resource pooling nghĩa là:", opts: ["Không chia sẻ","Chia sẻ tài nguyên","Không có tài nguyên","Không dùng mạng"], ans: 1 },
      { q: "Rapid elasticity thể hiện:", opts: ["Không mở rộng","Mở rộng nhanh tài nguyên","Không giảm tài nguyên","Không thay đổi"], ans: 1 },
      { q: "Measured service nghĩa là:", opts: ["Không đo lường","Tính phí theo sử dụng","Không có chi phí","Không có dữ liệu"], ans: 1 },
      { q: "Virtualization giúp:", opts: ["Xóa dữ liệu","Tạo máy ảo","Không dùng CPU","Không dùng RAM"], ans: 1 },
      { q: "Web 2.0 hỗ trợ:", opts: ["Phát triển ứng dụng web","Xóa dữ liệu","Không có giao diện","Không có user"], ans: 0 },
      { q: "Automation trong cloud giúp:", opts: ["Không điều phối","Tự động cấp phát tài nguyên","Xóa dữ liệu","Không quản lý"], ans: 1 },
      { q: "Một ưu điểm của cloud là:", opts: ["Không chia sẻ","Chia sẻ tài nguyên","Không truy cập","Không có mạng"], ans: 1 },
    ],
    hard: [
      { q: "Điểm cốt lõi của cloud computing là:", opts: ["Không dùng mạng","Cung cấp tài nguyên như dịch vụ","Không có dữ liệu","Không có user"], ans: 1 },
      { q: "Vì sao cloud giống dịch vụ điện/nước?", opts: ["Không có chi phí","Trả theo mức sử dụng","Không có dữ liệu","Không có user"], ans: 1 },
      { q: "Virtualization giúp tăng hiệu quả vì:", opts: ["Không dùng tài nguyên","Chia sẻ tài nguyên vật lý","Xóa dữ liệu","Không có CPU"], ans: 1 },
      { q: "Một nhược điểm của cloud là:", opts: ["Không có dữ liệu","Lo ngại bảo mật","Không có mạng","Không có user"], ans: 1 },
      { q: "Data center trong cloud có vai trò:", opts: ["Xóa dữ liệu","Lưu trữ và xử lý tài nguyên","Không có dữ liệu","Không có CPU"], ans: 1 },
      { q: "Tính co giãn của cloud liên quan đến:", opts: ["RAM","CPU","Khả năng mở rộng linh hoạt","Disk"], ans: 2 },
      { q: "Một thách thức của cloud là:", opts: ["Không có dữ liệu","Mất quyền kiểm soát","Không có mạng","Không có user"], ans: 1 },
      { q: "Cloud giúp tối ưu tài nguyên vì:", opts: ["Không dùng tài nguyên","Giảm tài nguyên nhàn rỗi","Xóa dữ liệu","Không có CPU"], ans: 1 },
      { q: "Công nghệ nền tảng của cloud gồm:", opts: ["Virtualization, distributed computing","CPU, RAM","BIOS","USB"], ans: 0 },
      { q: "Mô hình cloud phù hợp vì:", opts: ["Không có chi phí","Linh hoạt và hiệu quả","Không có dữ liệu","Không có user"], ans: 1 },
    ]
  },
  2: {
    name: "Chương 2",
    color: "c2",
    easy: [
      { q: "Điện toán đám mây cung cấp tài nguyên dưới dạng nào?", opts: ["Phần cứng cục bộ","Dịch vụ qua Internet","File offline","Thiết bị cá nhân"], ans: 1 },
      { q: "Một đặc điểm của cloud là người dùng không cần quan tâm đến:", opts: ["Chi phí","Cách vận hành hạ tầng","Dữ liệu","Ứng dụng"], ans: 1 },
      { q: "Cloud computing giúp:", opts: ["Tăng chi phí triển khai","Giảm chi phí và thời gian triển khai","Tăng độ phức tạp hệ thống","Giảm hiệu năng"], ans: 1 },
      { q: "AWS được Amazon cung cấp vào năm nào?", opts: ["2000","2003","2006","2010"], ans: 2 },
      { q: "Cloud computing phát triển từ ý tưởng nào ban đầu?", opts: ["Personal computing","Time-sharing","AI","Blockchain"], ans: 1 },
      { q: "Công nghệ quan trọng nhất trong cloud là:", opts: ["AI","IoT","Ảo hóa","Blockchain"], ans: 2 },
      { q: "Máy ảo chạy trên máy vật lý gọi là:", opts: ["Host","Guest","Node","Cluster"], ans: 1 },
      { q: "Hypervisor dùng để:", opts: ["Lưu trữ dữ liệu","Tạo máy ảo","Mã hóa dữ liệu","Tăng tốc CPU"], ans: 1 },
      { q: "Một lợi ích của cloud là:", opts: ["Không truy cập từ xa","Triển khai chậm","Truy cập mọi nơi qua Internet","Không chia sẻ tài nguyên"], ans: 2 },
      { q: "Cloud computing thuộc loại hệ thống:", opts: ["Tập trung đơn lẻ","Phân tán","Offline","Standalone"], ans: 1 },
    ],
    medium: [
      { q: "Theo NIST, cloud computing là mô hình cho phép:", opts: ["Truy cập cục bộ","Truy cập tài nguyên chia sẻ qua mạng","Chỉ lưu trữ dữ liệu","Chỉ xử lý dữ liệu"], ans: 1 },
      { q: "Đặc tính \"on-demand self-service\" nghĩa là:", opts: ["Người dùng phải yêu cầu thủ công","Người dùng tự cấp phát tài nguyên","Không cấp phát tài nguyên","Chỉ admin mới cấp"], ans: 1 },
      { q: "\"Broad network access\" thể hiện:", opts: ["Truy cập hạn chế","Truy cập rộng qua nhiều thiết bị","Không truy cập Internet","Chỉ PC"], ans: 1 },
      { q: "Resource pooling nghĩa là:", opts: ["Không chia sẻ tài nguyên","Tài nguyên được tập trung và chia sẻ","Chỉ một người dùng","Không ảo hóa"], ans: 1 },
      { q: "Rapid elasticity thể hiện:", opts: ["Không mở rộng được","Mở rộng tài nguyên nhanh theo nhu cầu","Chỉ mở rộng thủ công","Không giảm tài nguyên"], ans: 1 },
      { q: "Measured service nghĩa là:", opts: ["Không đo lường","Tính phí theo mức sử dụng","Miễn phí","Không kiểm soát"], ans: 1 },
      { q: "Web 2.0 trong cloud giúp:", opts: ["Giảm giao diện","Phát triển ứng dụng web dễ dàng","Không hỗ trợ web","Chỉ backend"], ans: 1 },
      { q: "Automation trong cloud giúp:", opts: ["Giảm hiệu suất","Tự động điều phối tài nguyên","Xóa dữ liệu","Không kiểm soát"], ans: 1 },
      { q: "Một ưu điểm của cloud là:", opts: ["Không mở rộng","Khả năng co giãn","Không chia sẻ","Không truy cập từ xa"], ans: 1 },
      { q: "Nhược điểm của cloud là:", opts: ["Không có chi phí","Lo ngại bảo mật","Không có dữ liệu","Không có dịch vụ"], ans: 1 },
    ],
    hard: [
      { q: "Điểm khác biệt chính giữa cloud và mô hình truyền thống là:", opts: ["Không dùng mạng","Không cần phần mềm","Cung cấp tài nguyên như dịch vụ","Không có dữ liệu"], ans: 2 },
      { q: "Vì sao tài nguyên cloud \"trong suốt\" với người dùng?", opts: ["Do không tồn tại","Do được ảo hóa và tập trung","Do không sử dụng","Do bị khóa"], ans: 1 },
      { q: "Vai trò của data center trong cloud là:", opts: ["Lưu trữ tài nguyên phân tán quy mô lớn","Chỉ lưu file nhỏ","Không lưu dữ liệu","Chỉ chạy ứng dụng"], ans: 0 },
      { q: "Virtualization giúp:", opts: ["Giảm số lượng máy ảo","Chia nhỏ tài nguyên vật lý thành nhiều máy ảo","Xóa dữ liệu","Không tối ưu tài nguyên"], ans: 1 },
      { q: "Một hạn chế của cloud là:", opts: ["Không mở rộng","Phụ thuộc nhà cung cấp","Không truy cập","Không có dịch vụ"], ans: 1 },
      { q: "Cloud giúp tiết kiệm chi phí vì:", opts: ["Không dùng tài nguyên","Chuyển CAPEX sang OPEX","Không cần phần mềm","Không có dữ liệu"], ans: 1 },
      { q: "Tính co giãn của cloud liên quan trực tiếp đến:", opts: ["CPU","Network","Khả năng mở rộng tài nguyên theo thời gian thực","RAM"], ans: 2 },
      { q: "Một vấn đề trong cloud là:", opts: ["Không có SLA","SLA phức tạp và phụ thuộc nhà cung cấp","Không có dữ liệu","Không có API"], ans: 1 },
      { q: "Mô hình cloud giải quyết vấn đề gì của hệ thống truyền thống?", opts: ["Thiếu dữ liệu","Tài nguyên nhàn rỗi và kém hiệu quả","Không có phần mềm","Không có mạng"], ans: 1 },
      { q: "Cloud computing được xem như \"dịch vụ tiện ích\" (utility computing) vì:", opts: ["Không tính phí","Giống điện/nước – dùng bao nhiêu trả bấy nhiêu","Không có mạng","Không có dữ liệu"], ans: 1 },
    ]
  },
  3: {
    name: "Lưu trữ & Xử lý DL",
    color: "c3",
    easy: [
      { q: "NFS là viết tắt của:", opts: ["Network File System","Node File Service","Network Fast Storage","New File System"], ans: 0 },
      { q: "AFS là viết tắt của:", opts: ["Advanced File System","Andrew File System","Automatic File Storage","Access File Server"], ans: 1 },
      { q: "Khi truy cập file trong AFS, dữ liệu được:", opts: ["Chỉ đọc từ server","Sao chép về máy client","Không truyền qua mạng","Xóa ngay"], ans: 1 },
      { q: "HDFS thuộc framework nào?", opts: ["Spark","Hadoop","AWS","Azure"], ans: 1 },
      { q: "HDFS được thiết kế để xử lý:", opts: ["Dữ liệu nhỏ","Dữ liệu trung bình","Dữ liệu lớn","Dữ liệu offline"], ans: 2 },
      { q: "GFS là hệ thống file của:", opts: ["Microsoft","Amazon","Google","IBM"], ans: 2 },
      { q: "Big Data thường có đặc điểm:", opts: ["Nhỏ, đơn giản","Lớn và phức tạp","Không thay đổi","Không lưu trữ"], ans: 1 },
      { q: "NoSQL dùng để:", opts: ["Thay thế hoàn toàn SQL","Lưu trữ dữ liệu phi cấu trúc","Xóa dữ liệu","Giảm mạng"], ans: 1 },
      { q: "HDFS hoạt động trên mô hình:", opts: ["Tập trung","Phân tán","Offline","Standalone"], ans: 1 },
      { q: "Hadoop sử dụng mô hình tính toán nào?", opts: ["Threading","MapReduce","Pipeline","Queue"], ans: 1 },
    ],
    medium: [
      { q: "Điểm khác biệt chính của AFS so với NFS là:", opts: ["Không dùng mạng","Sao chép toàn bộ file về client","Không lưu file","Không có server"], ans: 1 },
      { q: "Nhược điểm của AFS là:", opts: ["Không lưu file","Không đảm bảo nhất quán tuyệt đối","Không có client","Không có server"], ans: 1 },
      { q: "HDFS được thiết kế nhằm:", opts: ["Xử lý trên một máy","Xử lý dữ liệu phân tán trên nhiều node","Chỉ lưu trữ","Không xử lý dữ liệu"], ans: 1 },
      { q: "Một thành phần của HDFS là:", opts: ["CPU node","DataNode","GPU node","Web node"], ans: 1 },
      { q: "Ưu điểm chính của hệ phân tán là:", opts: ["Không mở rộng","Khả năng mở rộng cao","Không xử lý song song","Không chia sẻ"], ans: 1 },
      { q: "NoSQL phù hợp với dữ liệu:", opts: ["Quan hệ chặt chẽ","Phi cấu trúc hoặc bán cấu trúc","Chỉ số nguyên","Chỉ văn bản"], ans: 1 },
      { q: "MapReduce gồm hai bước chính:", opts: ["Read & Write","Map & Reduce","Load & Save","Input & Output"], ans: 1 },
      { q: "Một mục tiêu của HDFS là:", opts: ["Tối ưu dữ liệu nhỏ","Tăng độ tin cậy qua replication","Giảm số node","Không lưu trữ"], ans: 1 },
      { q: "Trong hệ phân tán, dữ liệu thường:", opts: ["Tập trung một nơi","Phân tán trên nhiều node","Không lưu","Chỉ RAM"], ans: 1 },
      { q: "GFS và HDFS đều hướng tới:", opts: ["Dữ liệu nhỏ","Dữ liệu lớn","Offline","Không mạng"], ans: 1 },
    ],
    hard: [
      { q: "Tại sao HDFS không phù hợp với file nhỏ?", opts: ["Không lưu được","Overhead quản lý block lớn","Không có RAM","Không có node"], ans: 1 },
      { q: "AFS cải thiện hiệu năng bằng cách:", opts: ["Không dùng mạng","Cache dữ liệu tại client","Xóa file","Giảm server"], ans: 1 },
      { q: "Nhược điểm của hệ phân tán là:", opts: ["Không mở rộng","Đồng bộ và nhất quán phức tạp","Không có dữ liệu","Không có node"], ans: 1 },
      { q: "Vai trò của DataNode trong HDFS là:", opts: ["Quản lý metadata","Lưu trữ dữ liệu","Điều phối job","Quản lý user"], ans: 1 },
      { q: "Big Data yêu cầu:", opts: ["Một máy mạnh","Hệ thống phân tán","Không cần mạng","Không lưu trữ"], ans: 1 },
      { q: "NoSQL không phù hợp với:", opts: ["Dữ liệu linh hoạt","Dữ liệu phi cấu trúc","Quan hệ phức tạp cần ACID chặt","Big Data"], ans: 2 },
      { q: "Một đặc điểm quan trọng của HDFS là:", opts: ["Không fault-tolerant","Tự động phục hồi lỗi","Không replication","Không scale"], ans: 1 },
      { q: "GFS và HDFS đều sử dụng:", opts: ["Block storage phân tán","File local","RAM only","SSD only"], ans: 0 },
      { q: "Trong MapReduce, Reduce dùng để:", opts: ["Chia dữ liệu","Tổng hợp kết quả","Đọc file","Xóa dữ liệu"], ans: 1 },
      { q: "Một thách thức của Big Data là:", opts: ["Dữ liệu ít","Xử lý và lưu trữ khối lượng lớn","Không có mạng","Không có thuật toán"], ans: 1 },
    ]
  },
  4: {
    name: "An toàn & Bảo mật",
    color: "c4",
    easy: [
      { q: "Một vấn đề lớn trong cloud computing là:", opts: ["Thiếu CPU","Thiếu RAM","An toàn và bảo mật","Không có mạng"], ans: 2 },
      { q: "Dữ liệu trong cloud thường được lưu ở:", opts: ["Máy cá nhân","Trung tâm dữ liệu","USB","RAM"], ans: 1 },
      { q: "Bảo mật trong cloud nhằm mục tiêu:", opts: ["Xóa dữ liệu","Bảo vệ dữ liệu và hệ thống","Giảm hiệu năng","Không cho truy cập"], ans: 1 },
      { q: "Một yếu tố của bảo mật là:", opts: ["Tốc độ","Tính bí mật","Màu sắc","Kích thước"], ans: 1 },
      { q: "Người dùng lo ngại điều gì khi dùng cloud?", opts: ["Không có dữ liệu","Mất quyền kiểm soát dữ liệu","Không có phần mềm","Không có CPU"], ans: 1 },
      { q: "Nhà cung cấp cloud có trách nhiệm:", opts: ["Không bảo mật","Bảo vệ hệ thống và dữ liệu","Xóa dữ liệu","Không quản lý"], ans: 1 },
      { q: "Một dạng tấn công phổ biến là:", opts: ["Rendering","Truy cập trái phép","Nén dữ liệu","Backup"], ans: 1 },
      { q: "Bảo mật truy cập thường dùng:", opts: ["Username/password","File text","CPU","GPU"], ans: 0 },
      { q: "Dữ liệu nhạy cảm cần:", opts: ["Không bảo vệ","Mã hóa","Xóa","Copy"], ans: 1 },
      { q: "Log hệ thống dùng để:", opts: ["Xóa dữ liệu","Theo dõi truy cập","Tăng CPU","Giảm RAM"], ans: 1 },
    ],
    medium: [
      { q: "Một nguyên nhân gây rủi ro bảo mật là:", opts: ["Dữ liệu tập trung","Dữ liệu phân tán","Không có mạng","Không có user"], ans: 0 },
      { q: "Bảo mật cloud cần đảm bảo:", opts: ["Chỉ hiệu năng","CIA (Confidentiality, Integrity, Availability)","Chỉ tốc độ","Chỉ lưu trữ"], ans: 1 },
      { q: "Authentication dùng để:", opts: ["Mã hóa","Xác thực người dùng","Lưu trữ","Xóa dữ liệu"], ans: 1 },
      { q: "Authorization dùng để:", opts: ["Xác định quyền truy cập","Xóa dữ liệu","Tăng tốc","Backup"], ans: 0 },
      { q: "Một giải pháp bảo mật là:", opts: ["Không kiểm soát truy cập","Kiểm soát truy cập","Không mã hóa","Không logging"], ans: 1 },
      { q: "Mã hóa dữ liệu giúp:", opts: ["Tăng dung lượng","Bảo vệ dữ liệu khỏi truy cập trái phép","Giảm bảo mật","Xóa dữ liệu"], ans: 1 },
      { q: "Một vấn đề của cloud là:", opts: ["Không có log","Khó kiểm soát log","Không có dữ liệu","Không có mạng"], ans: 1 },
      { q: "Backup dữ liệu giúp:", opts: ["Xóa dữ liệu","Khôi phục khi sự cố","Giảm bảo mật","Không lưu trữ"], ans: 1 },
      { q: "Một cơ chế bảo mật là:", opts: ["Firewall","CPU","GPU","RAM"], ans: 0 },
      { q: "SLA trong cloud liên quan đến:", opts: ["Thiết kế UI","Cam kết dịch vụ và bảo mật","CPU","RAM"], ans: 1 },
    ],
    hard: [
      { q: "Thách thức lớn của bảo mật cloud là:", opts: ["Không có dữ liệu","Mất quyền kiểm soát hạ tầng","Không có CPU","Không có mạng"], ans: 1 },
      { q: "Vì sao dữ liệu tập trung gây rủi ro?", opts: ["Khó lưu trữ","Trở thành mục tiêu tấn công lớn","Không truy cập được","Không có mạng"], ans: 1 },
      { q: "Một giải pháp chống truy cập trái phép là:", opts: ["Không dùng password","Multi-factor authentication","Không login","Không lưu dữ liệu"], ans: 1 },
      { q: "Integrity nghĩa là:", opts: ["Bảo mật dữ liệu","Toàn vẹn dữ liệu","Sẵn sàng","Truy cập"], ans: 1 },
      { q: "Availability nghĩa là:", opts: ["Bí mật","Toàn vẹn","Sẵn sàng truy cập","Mã hóa"], ans: 2 },
      { q: "Một rủi ro của cloud là:", opts: ["Không có dữ liệu","Phụ thuộc nhà cung cấp","Không có mạng","Không có CPU"], ans: 1 },
      { q: "Logging quan trọng vì:", opts: ["Xóa dữ liệu","Phát hiện và truy vết sự cố","Tăng RAM","Giảm CPU"], ans: 1 },
      { q: "Một kiến trúc bảo mật tốt cần:", opts: ["Không phân quyền","Phân lớp bảo mật","Không mã hóa","Không backup"], ans: 1 },
      { q: "Dữ liệu khi truyền qua mạng cần:", opts: ["Không bảo vệ","Mã hóa (encryption in transit)","Xóa","Copy"], ans: 1 },
      { q: "Một hạn chế của bảo mật cloud là:", opts: ["Không có giải pháp","Khó kiểm soát hoàn toàn bởi người dùng","Không có dữ liệu","Không có mạng"], ans: 1 },
    ]
  },
  5: {
    name: "Sử dụng Dịch vụ",
    color: "c5",
    easy: [
      { q: "SaaS là viết tắt của:", opts: ["Software as a Service","Storage as a System","Server as a Software","Service as a Software"], ans: 0 },
      { q: "PaaS là viết tắt của:", opts: ["Platform as a Service","Program as a Service","Processing as a System","Platform and Software"], ans: 0 },
      { q: "IaaS là viết tắt của:", opts: ["Infrastructure as a Service","Internet as a Service","Internal as a System","Interface as a Service"], ans: 0 },
      { q: "SaaS cung cấp cho người dùng:", opts: ["Phần cứng","Phần mềm hoàn chỉnh","CPU","RAM"], ans: 1 },
      { q: "PaaS cung cấp:", opts: ["Hệ điều hành và môi trường phát triển","Chỉ phần mềm","Chỉ dữ liệu","Không cung cấp gì"], ans: 0 },
      { q: "IaaS cung cấp:", opts: ["Ứng dụng hoàn chỉnh","Hạ tầng như máy chủ, lưu trữ","Chỉ database","Chỉ web"], ans: 1 },
      { q: "Người dùng SaaS thường:", opts: ["Phải cài đặt hệ điều hành","Chỉ sử dụng ứng dụng qua web","Quản lý server","Viết driver"], ans: 1 },
      { q: "Ví dụ SaaS là:", opts: ["Google Docs","CPU","RAM","BIOS"], ans: 0 },
      { q: "Ví dụ IaaS là:", opts: ["Máy ảo","File text","Word","Excel offline"], ans: 0 },
      { q: "Người dùng PaaS thường là:", opts: ["Người dùng cuối","Lập trình viên","Người bán hàng","Người không dùng máy tính"], ans: 1 },
    ],
    medium: [
      { q: "Điểm khác biệt chính giữa SaaS và PaaS là:", opts: ["SaaS cung cấp nền tảng","SaaS cung cấp ứng dụng hoàn chỉnh","PaaS không có dịch vụ","SaaS không có phần mềm"], ans: 1 },
      { q: "PaaS giúp lập trình viên:", opts: ["Không cần viết code","Phát triển ứng dụng nhanh hơn","Không cần server","Không cần dữ liệu"], ans: 1 },
      { q: "IaaS cho phép người dùng:", opts: ["Không quản lý gì","Tự cấu hình máy ảo","Không truy cập","Không cài OS"], ans: 1 },
      { q: "Trong IaaS, người dùng chịu trách nhiệm:", opts: ["Hạ tầng vật lý","Hệ điều hành và ứng dụng","Không gì","Chỉ mạng"], ans: 1 },
      { q: "SaaS giảm chi phí vì:", opts: ["Không dùng phần mềm","Không cần cài đặt và bảo trì","Không có mạng","Không có dữ liệu"], ans: 1 },
      { q: "PaaS phù hợp với:", opts: ["Người không biết lập trình","Nhà phát triển phần mềm","Người dùng cá nhân","Không ai dùng"], ans: 1 },
      { q: "IaaS có tính linh hoạt vì:", opts: ["Không cấu hình được","Tùy chỉnh tài nguyên theo nhu cầu","Không mở rộng","Không truy cập"], ans: 1 },
      { q: "SaaS hoạt động chủ yếu qua:", opts: ["USB","Internet","CPU","RAM"], ans: 1 },
      { q: "Một lợi ích của PaaS là:", opts: ["Không cần platform","Giảm thời gian phát triển","Không cần code","Không có database"], ans: 1 },
      { q: "IaaS thường dùng trong:", opts: ["Game offline","Triển khai server","Soạn thảo văn bản","Vẽ hình"], ans: 1 },
    ],
    hard: [
      { q: "Sự khác biệt chính giữa IaaS và PaaS là:", opts: ["IaaS không có server","PaaS trừu tượng hóa hạ tầng nhiều hơn","IaaS cung cấp ứng dụng","PaaS không có nền tảng"], ans: 1 },
      { q: "Trong SaaS, người dùng KHÔNG cần:", opts: ["Internet","Trình duyệt","Quản lý hạ tầng","Dữ liệu"], ans: 2 },
      { q: "PaaS giúp giảm độ phức tạp bằng cách:", opts: ["Xóa code","Ẩn quản lý hạ tầng","Xóa database","Xóa network"], ans: 1 },
      { q: "IaaS phù hợp khi:", opts: ["Chỉ cần dùng ứng dụng","Cần kiểm soát hệ thống","Không cần server","Không có dữ liệu"], ans: 1 },
      { q: "SaaS có hạn chế là:", opts: ["Không dùng Internet","Ít tùy chỉnh","Không có phần mềm","Không có user"], ans: 1 },
      { q: "PaaS thường cung cấp:", opts: ["OS, middleware, runtime","CPU vật lý","RAM vật lý","BIOS"], ans: 0 },
      { q: "IaaS yêu cầu người dùng có kiến thức:", opts: ["Thiết kế UI","Quản trị hệ thống","Vẽ hình","Word"], ans: 1 },
      { q: "Một ví dụ điển hình của PaaS là:", opts: ["Google App Engine","RAM","CPU","BIOS"], ans: 0 },
      { q: "Sự phân tầng dịch vụ cloud giúp:", opts: ["Giảm phân loại","Phân chia trách nhiệm rõ ràng","Không có lợi","Không dùng được"], ans: 1 },
      { q: "Trong mô hình cloud, mức độ kiểm soát giảm dần theo thứ tự:", opts: ["SaaS → PaaS → IaaS","IaaS → PaaS → SaaS","PaaS → SaaS → IaaS","Không xác định"], ans: 1 },
    ]
  }
};

const CHAPTER_COLORS = { 1: '#58a6ff', 2: '#3fb950', 3: '#f97316', 4: '#f85149', 5: '#8b5cf6' };
const CHAPTER_NAMES_SHORT = { 1: 'Chương MĐ', 2: 'Chương 2', 3: 'Chương 3', 4: 'Chương 4', 5: 'Chương 5' };
const DIFF_NAMES = { easy: 'Dễ', medium: 'Trung bình', hard: 'Khó' };

// Count total questions in bank
function getTotalBankSize() {
  return Object.values(QUESTION_BANK).reduce((sum, ch) => {
    return sum + ch.easy.length + ch.medium.length + ch.hard.length;
  }, 0);
}